# print("\n\n\033[1mLeaderboard\033[0m")
# print(f"\033[4mUsername\033[0m               ""\033[4mTop Score\033[0m")
# for i in range(0,len(user_info)):
#   print(user_info[i][0].ljust(22),  user_info[i][2])
print("Name".ljust(28),"xyz")
print("Games".ljust(28),"xyz")
print("Minutes".ljust(28),"xyz")
print("Goals".ljust(28),"xyz")
print("Expected Goals".ljust(28),"xyz")
print("Assists".ljust(28),"xyz")
print("Expected assists".ljust(28),"xyz")
print("Shots".ljust(28),"xyz")
print("Key Passes".ljust(28),"xyz")
print("Yellow Cards".ljust(28),"xyz")
print("Red Cards".ljust(28),"xyz")
print("Position".ljust(28),"xyz")
print("Team Name".ljust(28),"xyz")
print("Non Penalty Goals".ljust(28),"xyz")
print("Non Penalty Expected Goals".ljust(28),"xyz")
print("Expected Goals Chain".ljust(28),"xyz")
print("Expected Goals Build-up".ljust(28),"xyz")
print("Score".ljust(28),"xyz")
      